on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build_test:
    uses: ./.github/workflows/build-test.yaml

  release:
    needs: [build_test]
    uses: ./.github/workflows/release.yaml
