name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-linux:
    name: Create Release x86_64
    runs-on: ${{ matrix.os }}
    env:
      CABAL_VER: 3.6.2.0
      CACHE_VER: 1
      MACOSX_DEPLOYMENT_TARGET: 10.13
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ARTIFACT: "i386-linux-ghcup"
            GHC_VER: 8.10.7
            ARCH: 32
          - os: ubuntu-latest
            ARTIFACT: "x86_64-linux-ghcup"
            GHC_VER: 8.10.7
            ARCH: 64
          - os: [self-hosted, macOS, aarch64]
            ARTIFACT: "aarch64-apple-darwin-ghcup"
            GHC_VER: 9.2.5
            ARCH: 64
          - os: macOS-10.15
            ARTIFACT: "x86_64-apple-darwin-ghcup"
            GHC_VER: 9.2.5
            ARCH: 64
          - os: windows-latest
            ARTIFACT: "x86_64-mingw64-ghcup"
            GHC_VER: 8.10.7
            ARCH: 64
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - if: matrix.ARCH == '32' && runner.os == 'Linux'
        name: Run release (32 bit linux)
        uses: docker://i386/alpine:3.12
        with:
          args: sh .github/scripts/release.sh
        env:
          ARTIFACT: ${{ matrix.ARTIFACT }}
          ARCH: ${{ matrix.ARCH }}
          GHC_VER: ${{ matrix.GHC_VER }}

      - if: matrix.ARCH == '64' && runner.os == 'Linux'
        name: Run release (64 bit linux)
        uses: docker://alpine:3.12
        with:
          args: sh .github/scripts/release.sh
        env:
          ARTIFACT: ${{ matrix.ARTIFACT }}
          ARCH: ${{ matrix.ARCH }}
          GHC_VER: ${{ matrix.GHC_VER }}

      - if: runner.os != 'Linux'
        name: Run release (windows/mac)
        run: bash .github/scripts/release.sh
        env:
          ARTIFACT: ${{ matrix.ARTIFACT }}
          ARCH: ${{ matrix.ARCH }}
          GHC_VER: ${{ matrix.GHC_VER }}

      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./out/*
            ./dist-newstyle/cache/plan.json

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./out/*
            ./dist-newstyle/cache/plan.json
